// README rendering from the parsed doc model.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// generateReadme writes a README.md to the module directory.
// Always overwrites any existing README.md.
func generateReadme(mod Module) (err error) {
	path := filepath.Join(mod.Dir, "README.md")
	absPath, _ := filepath.Abs(path)
	f, err := os.OpenFile(absPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()

	w := bufio.NewWriter(f)

	_, _ = fmt.Fprintf(w, "# %s Service\n\n", mod.Name)
	// Kept as a bold paragraph (not a blockquote) so it does not sit adjacent to
	// the [!IMPORTANT] blockquote below — two blockquotes separated by a blank
	// line would trip markdownlint MD028 (blank line inside blockquote).
	_, _ = fmt.Fprintf(w, "**Package:** `%s`\n\n", mod.Package)
	_, _ = fmt.Fprintf(w, "> [!IMPORTANT]\n")
	_, _ = fmt.Fprintf(w, "> Auto-generated by `protodoc`. Do not edit manually.\n\n")

	// Services.
	if len(mod.Services) > 0 {
		_, _ = fmt.Fprintf(w, "## Services\n\n")
		for _, svc := range mod.Services {
			_, _ = fmt.Fprintf(w, "### %s\n\n", svc.Name)
			if svc.Comment != "" {
				_, _ = fmt.Fprintf(w, "%s\n\n", svc.Comment)
			}
			if len(svc.RPCs) > 0 {
				mdTableHeader(w, "Method", "Request", "Response", "Description")
				for _, rpc := range svc.RPCs {
					stream := ""
					if rpc.ServerStream {
						stream = "stream "
					}
					_, _ = fmt.Fprintf(w, "| `%s` | `%s` | `%s%s` | %s |\n",
						rpc.Name, rpc.Request, stream, rpc.Response, rpc.Comment)
				}
				_, _ = fmt.Fprintf(w, "\n")
			}
		}
	}

	// Messages.
	if len(mod.Messages) > 0 {
		_, _ = fmt.Fprintf(w, "## Messages\n\n")
		for _, msg := range mod.Messages {
			_, _ = fmt.Fprintf(w, "### %s\n\n", msg.Name)
			if msg.Comment != "" {
				_, _ = fmt.Fprintf(w, "%s\n\n", msg.Comment)
			}
			if len(msg.Fields) > 0 {
				mdTableHeader(w, "Field", "Type", "Behavior", "Description")
				for _, field := range msg.Fields {
					beh := field.Behavior
					if beh == "" && field.Required {
						beh = "REQUIRED"
					}
					if beh != "" {
						beh = "`" + beh + "`"
					} else {
						beh = "-"
					}
					typ := field.Type
					if field.Repeated {
						typ = "repeated " + typ
					}
					_, _ = fmt.Fprintf(w, "| `%s` | `%s` | %s | %s |\n",
						field.Name, typ, beh, field.Comment)
				}
				_, _ = fmt.Fprintf(w, "\n")
			}
		}
	}

	// Enums.
	if len(mod.Enums) > 0 {
		_, _ = fmt.Fprintf(w, "## Enums\n\n")
		for _, en := range mod.Enums {
			_, _ = fmt.Fprintf(w, "### %s\n\n", en.Name)
			if en.Comment != "" {
				_, _ = fmt.Fprintf(w, "%s\n\n", en.Comment)
			}
			if len(en.Values) > 0 {
				mdTableHeader(w, "Value", "Number", "Description")
				for _, val := range en.Values {
					_, _ = fmt.Fprintf(w, "| `%s` | %s | %s |\n", val.Name, val.Number, val.Comment)
				}
				_, _ = fmt.Fprintf(w, "\n")
			}
		}
	}

	_, _ = fmt.Fprintf(w, "---\n\n")
	_, _ = fmt.Fprintf(w, "© 2026 The Protobuf Project Authors | Apache 2.0 License\n")

	// bufio.Writer accumulates a sticky error across all the writes above;
	// Flush surfaces it as the single write-error checkpoint.
	return w.Flush()
}

// --- Helpers ---

func titleCase(s string) string {
	words := strings.Split(s, "_")
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

func simplifyType(t string) string {
	// Strip package prefixes for readability.
	parts := strings.Split(t, ".")
	return parts[len(parts)-1]
}

// extractFieldBehavior finds (google.api.field_behavior) = X in the field text.
func extractFieldBehavior(fullField string) string {
	matches := reFieldBehavior.FindAllStringSubmatch(fullField, -1)
	if len(matches) == 0 {
		return ""
	}
	for _, m := range matches {
		if len(m) >= 2 && (m[1] == "REQUIRED" || m[1] == "IDENTIFIER") {
			return m[1]
		}
	}
	return matches[0][1]
}
