// summary.go contains the cross-module documentation for protodoc: the
// top-level README.md that summarises every module and visualises the import
// relationships between them as a Mermaid graph.
//
// It is part of the same `main` package as main.go and reuses the Module model
// populated there. main.go calls generateRootReadme after it has parsed every
// module and written the per-module READMEs.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// mdTableHeader writes a GitHub-flavored Markdown table header: the column
// titles followed by the delimiter row. Every pipe is padded with a single
// space on each side and the delimiter cells use "---", which keeps the output
// consistent with the data rows and satisfies markdownlint's MD060
// (table-column-style) check.
//
// Example, mdTableHeader(w, "A", "B") writes:
//
//	| A | B |
//	| --- | --- |
func mdTableHeader(w io.Writer, cols ...string) {
	_, _ = fmt.Fprintf(w, "| %s |\n", strings.Join(cols, " | "))
	seps := make([]string, len(cols))
	for i := range seps {
		seps[i] = "---"
	}
	_, _ = fmt.Fprintf(w, "| %s |\n", strings.Join(seps, " | "))
}

// generateRootReadme writes <protoDir>/README.md: a summary table of every
// module plus a Mermaid graph of the in-repository import relationships
// between them. External imports (google.*, mcp.*, google/protobuf/*) are
// intentionally excluded so the graph shows only first-party coupling.
//
// The file is always overwritten and is emitted in a markdownlint-clean style.
func generateRootReadme(protoDir string, modules []Module) (err error) {
	// Stable, deterministic output regardless of filesystem walk order.
	sort.Slice(modules, func(i, j int) bool {
		return modules[i].Package < modules[j].Package
	})

	// Index by package so dependency edges (discovered as import paths) can be
	// resolved back to the owning module for labels, node IDs, and filtering.
	byPackage := make(map[string]Module, len(modules))
	for _, m := range modules {
		byPackage[m.Package] = m
	}

	f, err := os.OpenFile(filepath.Join(protoDir, "README.md"), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()

	w := bufio.NewWriter(f)

	// --- Header ---
	_, _ = fmt.Fprintf(w, "# Protobuf RFC Reference\n\n")
	_, _ = fmt.Fprintf(w, "> [!IMPORTANT]\n")
	_, _ = fmt.Fprintf(w, "> Auto-generated by `protodoc`. Do not edit manually.\n\n")
	_, _ = fmt.Fprintf(w, "Every protobuf module under `%s/`. Each row links to that module's generated reference.\n\n", protoDir)

	// --- Module summary table ---
	_, _ = fmt.Fprintf(w, "## Modules\n\n")
	mdTableHeader(w, "Module", "Package", "Services", "Messages", "Enums", "Reference")
	var totSvc, totMsg, totEnum int
	for _, m := range modules {
		link := moduleReadmeLink(protoDir, m)
		_, _ = fmt.Fprintf(w, "| %s | `%s` | %d | %d | %d | [README](%s) |\n",
			m.Name, m.Package, len(m.Services), len(m.Messages), len(m.Enums), link)
		totSvc += len(m.Services)
		totMsg += len(m.Messages)
		totEnum += len(m.Enums)
	}
	_, _ = fmt.Fprintf(w, "| **Total** | _%d modules_ | %d | %d | %d | |\n\n",
		len(modules), totSvc, totMsg, totEnum)

	// --- Dependency graph ---
	_, _ = fmt.Fprintf(w, "## Dependency graph\n\n")
	_, _ = fmt.Fprintf(w, "Import relationships between modules in this repository. External dependencies (`google.*`, `buf.*`) are omitted.\n\n")
	_, _ = fmt.Fprintf(w, "```mermaid\n")
	_, _ = fmt.Fprintf(w, "graph LR\n")

	// Nodes: one per module, labelled with its display name and package.
	for _, m := range modules {
		_, _ = fmt.Fprintf(w, "    %s[\"%s<br/>%s\"]\n", nodeID(m.Package), m.Name, m.Package)
	}

	// Edges: module -> imported local module, de-duplicated.
	seen := make(map[string]bool)
	hasEdge := false
	for _, m := range modules {
		for _, dep := range localDeps(m, byPackage) {
			key := m.Package + "->" + dep
			if seen[key] {
				continue
			}
			seen[key] = true
			hasEdge = true
			_, _ = fmt.Fprintf(w, "    %s --> %s\n", nodeID(m.Package), nodeID(dep))
		}
	}
	if !hasEdge {
		_, _ = fmt.Fprintf(w, "    %%%% no local cross-module imports\n")
	}
	_, _ = fmt.Fprintf(w, "```\n\n")

	// --- Footer ---
	_, _ = fmt.Fprintf(w, "---\n\n")
	_, _ = fmt.Fprintf(w, "© 2026 The Protobuf Project Authors | Apache 2.0 License\n")

	// bufio.Writer accumulates a sticky error across all the writes above;
	// Flush surfaces it as the single write-error checkpoint.
	return w.Flush()
}

// localDeps returns the sorted, de-duplicated set of first-party module
// packages that mod imports, excluding self-imports and any import that does
// not resolve to a known module (e.g. google/* or mcp/* third-party deps).
func localDeps(mod Module, byPackage map[string]Module) []string {
	set := make(map[string]bool)
	for _, imp := range mod.Imports {
		pkg := importPathToPackage(imp)
		if pkg == mod.Package {
			continue // intra-module import
		}
		if _, ok := byPackage[pkg]; !ok {
			continue // external / unknown dependency
		}
		set[pkg] = true
	}
	deps := make([]string, 0, len(set))
	for pkg := range set {
		deps = append(deps, pkg)
	}
	sort.Strings(deps)
	return deps
}

// importPathToPackage converts a proto import path such as
// "protobuf/rfc6350/vcard/v1/types.proto" into its proto package
// "protobuf.rfc6350.vcard.v1" by dropping the file name and joining the
// remaining directory segments with dots. This relies on the convention
// that the import directory layout mirrors the proto package path.
func importPathToPackage(imp string) string {
	return strings.ReplaceAll(path.Dir(imp), "/", ".")
}

// moduleReadmeLink returns the path to a module's README.md relative to the
// root README at <protoDir>/README.md, using forward slashes so the link works
// on every platform and in rendered Markdown.
func moduleReadmeLink(protoDir string, mod Module) string {
	rel, err := filepath.Rel(protoDir, mod.Dir)
	if err != nil {
		rel = mod.Dir
	}
	return filepath.ToSlash(filepath.Join(rel, "README.md"))
}

// nodeID turns a proto package into a Mermaid-safe node identifier by replacing
// every character that is not a letter or digit with an underscore, e.g.
// "protobuf.rfc6350.vcard.v1" -> "protobuf_rfc6350_vcard_v1".
func nodeID(pkg string) string {
	var b strings.Builder
	for _, r := range pkg {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}
